name: Build and Deploy Documentation

on:
  push:
    branches:
      - main   # or master

permissions:
  contents: read
  pages: write
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:

  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Install dependencies
        run: uv sync --extra docs

      - name: Build files
        working-directory: ./docs
        run: uv run sphinx-build -b html . _build/html

      - name: Upload HTML artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
